<?php

namespace babld\avito\models;

use yii\db\ActiveRecord;

/**
 * @property string $field_name
 * @property string $value
 * @property string $item_id
 * @property string $model_name
 * @property int id
 */
class Avito extends ActiveRecord
{
    const string SCENARIO_REQUIRED = 'required';

    public static function tableName()
    {
        return '{{%avito}}';
    }

    public function rules()
    {
//        return [
//            ['value', 'required', 'on' => self::SCENARIO_REQUIRED],
//        ];
        return parent::rules();
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}